language: c
compiler:
   - clang
   - gcc

before_install:
   - sudo apt-get install protobuf-c-compiler libprotobuf-c0-dev libprotobuf-c0 libssh2-1 libssh2-1-dev

script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON .. && make && ctest -V
