language: c
compiler:
   - clang
   - gcc

before_install:
   - sudo apt-get install protobuf-c-compiler libprotobuf-c0-dev libprotobuf-c0

script: mkdir build && cd build && cmake .. && make && ctest ..
