language: c
compiler:
   - clang
   - gcc

before_install:
   - sudo apt-get install protobuf-c-compiler libprotobuf-c0-dev libprotobuf-c0 libssh-4 libssh-dev doxygen

script:
   - mkdir -p build/doc
   - cd build
   - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON ..
   - make
   - ctest -V
   - make doc
   - cat doxylog && [ ! -s doxylog ]

env:
    - CFLAGS="-O3"
    - CFLAGS="-O2"
    -
