language: objective-c
compiler:
   - clang

before_install:
   - brew install gettext cmake glib protobuf protobuf-c libssh doxygen
   - brew link -f gettext

script:
   - mkdir -p build/doc
   - cd build
   - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON ..
   - make
   - ctest -V
   - make doc
   - cat doxylog && [ ! -s doxylog ]

env:
    - CFLAGS="-O3"
    - CFLAGS="-O2"
    -
