language: objective-c
compiler:
   - clang
   - gcc

before_install:
   - brew install cmake glib protobuf protobuf-c libssh doxygen

script:
   - mkdir -p build/doc
   - cd build
   - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON ..
   - make
   - ctest -V
   - make doc
   - cat doxylog
   - [ ! -s doxylog ]

env:
    - CFLAGS="-O3"
    - CFLAGS="-O2"
    -
